Mobile push notifications
open-company/open-company-auth pull request #89
Opened 2019-08-09 17:03 UTC by cjsauer

Trello: https://trello.com/c/Vn56Ry3Q/2160-mobile-push-notifications

2019-08-09 17:05 UTC, cjsauer commented
![](https://github.trello.services/images/mini-trello-icon.png) [Mobile push notifications](https://trello.com/c/Vn56Ry3Q/2160-mobile-push-notifications)

2019-08-26 13:13 UTC, bago2k4 requested changes
I think we should add the expo push token also to the JWT so the services can get it directly from the requests the users are doing. No need for them to go read it in the DB.

To do so you need to add it to the JWT claims (in lib oc.lib.jwt) and also in the client you need to force a JWT refresh every time a token change (added removed etc).

If a token gets invalidated the user needs to wait for the token to expire to get it cleared.

We should adjust this and invalidate a JWT on the fly but for now we just wait for them to expire.

2019-08-26 13:13 UTC, bago2k4 commented on src/oc/auth/api/users.clj
> +                         config/passphrase))
This shouldn't be needed if you use `api-common/open-company-authenticated-resource`

2019-08-26 13:13 UTC, bago2k4 commented on src/oc/auth/api/users.clj
> +                        :post (fn [ctx] (-> ctx :user :user-id))})
Here you should use something like: `allow-user-and-team-admins` or add your own to make sure only the authenticated user can change the push token (not sure an admin of the same org should be able to change it).

2019-08-26 16:43 UTC, cjsauer commented
@bago2k4 should be good for review again

2019-08-26 17:59 UTC, bago2k4 commented
After discussion in Slack we decided we are good to go w/o push tokens in the JWT for the moment, the other fixes are still required though.

2019-08-26 19:05 UTC, cjsauer commented
@bago2k4 other fixes were made already. Did I miss anything?

2019-08-26 20:21 UTC, bago2k4 commented
@cjsauer i didn't see your commits/messages, probably GH page didn't update live and i didn't refresh.. will take a look in the morning. thanks

2019-08-27 11:43 UTC, bago2k4 commented on src/oc/auth/async/expo.clj
> +    (determine-bad-push-tokens push-notifications tickets receipts)
@cjsauer maybe it's only this code that is wrong but running this from the repl i get this map as result of `determine-bad-push-tokens` and as you can see the user-id are nil:
`{"TOKEN_B" nil, "TOKEN_C" nil}`
Maybe i did something wrong or maybe the starting map here is wrong.
I am starting now to do the test steps so i'll be testing the token remove on Android soon.

2019-08-27 16:50 UTC, cjsauer commented on src/oc/auth/async/expo.clj
> +    (determine-bad-push-tokens push-notifications tickets receipts)
@bago2k4 hmm...I just ran the same `let` expression at my REPL and received the proper response, a set of two push tokens: `#{"TOKEN_C" "TOKEN_B"}`. I'm not sure what would cause you to get a map...

2019-08-27 17:13 UTC, bago2k4 approved these changes

2019-08-27 17:13 UTC, merged